name: apiverve_fullyqualifieddomain
description: Fully Qualified Domain Name is a simple tool for getting the fully qualified domain name (FQDN) of an IP. It returns the fully qualified domain name of the ip provided.
version: 1.1.14
homepage: https://apiverve.com/marketplace/fullyqualifieddomain?utm_source=dart&utm_medium=homepage
repository: https://github.com/apiverve/fullyqualifieddomain-api/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
